title: Laxmi Khilnani - Data Scientist & Full-Stack Developer
description: Portfolio showcasing skills, projects, and achievements of Laxmi Khilnani.
theme: minima
author: Laxmi Khilnani
url: https://laxmikhilnani.github.io
